name: responsive_framework
description: Easily make Flutter apps responsive. Automatically adapt UI to different screen sizes. Responsiveness made simple.
version: 0.0.6
homepage: https://codelessly.com
repository: https://github.com/Codelessly/ResponsiveFramework
issue_tracker: https://github.com/Codelessly/ResponsiveFramework/issues
documentation: https://github.com/Codelessly/ResponsiveFramework

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: