name: responsive_framework
description: Easily make Flutter apps responsive. Automatically adapt UI to different screen sizes. Responsiveness made simple.
version: 1.1.1
homepage: https://codelessly.com
repository: https://github.com/Codelessly/ResponsiveFramework
documentation: https://github.com/Codelessly/ResponsiveFramework

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0 # Do not force latest version to prevent dependency conflicts.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter: